### POST signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name":"SH",
  "phone":"(010) 111 4544",
  "email":"mangrove.sh3@gmail.com",
  "password":"p@ssw0rd"
}

### POST signup
POST http://localhost:3000/auth/signup/REALTOR
Content-Type: application/json

{
  "name":"SH",
  "phone":"(010) 111 4544",
  "email":"mangrove.sh3@gmail.com",
  "password":"p@ssw0rd",
  "productKey": "$2a$10$kllb3McB4N0yRFZ4/c6ETeeYTn0YxMffs8XJAw5dttQb5aBz7mTp6"
}

### POST signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email":"mangrove.sh3@gmail.com",
  "password":"p@ssw0rd"
}

### POST Generate Product Key
POST http://localhost:3000/auth/key
Content-Type: application/json

{
  "email":"mangrove.sh3@gmail.com",
  "userType":"REALTOR"
}