### Get All Homes
GET http://localhost:3000/home?city=경기도&minPrice=10000
Content-Type: application/json; charset=utf-8

### Get Home By Id
GET http://localhost:3000/home/1
Content-Type: application/json; charset=utf-8

### Create Home
POST http://localhost:3000/home
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU0giLCJpZCI6NSwiaWF0IjoxNjg5MDg2MjAzLCJleHAiOjE2OTI2ODYyMDN9.W5KWfQ14zHGZUIi6MIfxzVhMBuCrRUfiDJbGBFiiOHo

{
  "address": "김포시 풍무로 50",
  "numberOfBedrooms": 3,
  "numberOfBathrooms": 2,
  "city": "경기도",
  "price": 19000,
  "landSize": 300,
  "propertyType": "RESIDENTIAL",
  "images": [
    {
      "url": "image1"
    }
    , {
      "url": "image2"
    }
  ]
}

### Update Home
PUT http://localhost:3000/home/3
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU0giLCJpZCI6NSwiaWF0IjoxNjg5MDg2MjAzLCJleHAiOjE2OTI2ODYyMDN9.W5KWfQ14zHGZUIi6MIfxzVhMBuCrRUfiDJbGBFiiOHo

{
  "address": "김포시 풍무로 51"
}

### Delete Home
DELETE http://localhost:3000/home/3
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU0giLCJpZCI6NSwiaWF0IjoxNjg5MDg2MjAzLCJleHAiOjE2OTI2ODYyMDN9.W5KWfQ14zHGZUIi6MIfxzVhMBuCrRUfiDJbGBFiiOHo