### Get All Homes
GET http://localhost:3000/home?city=경기도&minPrice=10000
Content-Type: application/json; charset=utf-8

### Get Home By Id
GET http://localhost:3000/home/1

### Create Home
POST http://localhost:3000/home
Content-Type: application/json; charset=utf-8

### Update Home
PUT http://localhost:3000/home/1

### Delete Home
DELETE http://localhost:3000/home/1